// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913130224_AddTrancheDisplayOrder")]
    partial class AddTrancheDisplayOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Api.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Api.Domain.CashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountThb")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("amount_thb");

                    b.Property<int?>("CounterAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("counter_account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<decimal>("FxRateUsed")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("fx_rate_used");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.HasKey("Id")
                        .HasName("pk_cash_flows");

                    b.HasIndex("CounterAccountId")
                        .HasDatabaseName("ix_cash_flows_counter_account_id");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("ix_cash_flows_occurred_on");

                    b.HasIndex("AccountId", "OccurredOn")
                        .HasDatabaseName("ix_cash_flows_account_id_occurred_on");

                    b.ToTable("cash_flows", (string)null);
                });

            modelBuilder.Entity("Api.Domain.EntryPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date")
                        .HasColumnName("plan_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_entry_plans");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_entry_plans_account_id");

                    b.ToTable("entry_plans", (string)null);
                });

            modelBuilder.Entity("Api.Domain.PlanTranche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("budget");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("Filled")
                        .HasColumnType("boolean")
                        .HasColumnName("filled");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("SlPrice")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("sl_price");

                    b.Property<decimal?>("TpPrice")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("tp_price");

                    b.HasKey("Id")
                        .HasName("pk_plan_tranches");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_plan_tranches_plan_id");

                    b.ToTable("plan_tranches", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<decimal>("FxRateUsed")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("fx_rate_used");

                    b.Property<decimal>("NativeAmount")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("native_amount");

                    b.Property<string>("NativeCurrency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("native_currency");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal>("ValueThb")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("value_thb");

                    b.HasKey("Id")
                        .HasName("pk_snapshots");

                    b.HasIndex("AccountId", "AsOfDate")
                        .IsUnique()
                        .HasDatabaseName("ix_snapshots_account_id_as_of_date");

                    b.ToTable("snapshots", (string)null);
                });

            modelBuilder.Entity("Api.Domain.CashFlow", b =>
                {
                    b.HasOne("Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cash_flows_accounts_account_id");

                    b.HasOne("Api.Domain.Account", "CounterAccount")
                        .WithMany()
                        .HasForeignKey("CounterAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cash_flows_accounts_counter_account_id");

                    b.Navigation("Account");

                    b.Navigation("CounterAccount");
                });

            modelBuilder.Entity("Api.Domain.EntryPlan", b =>
                {
                    b.HasOne("Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_entry_plans_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Api.Domain.PlanTranche", b =>
                {
                    b.HasOne("Api.Domain.EntryPlan", "Plan")
                        .WithMany("Tranches")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_tranches_entry_plans_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Api.Domain.Snapshot", b =>
                {
                    b.HasOne("Api.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_snapshots_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Api.Domain.EntryPlan", b =>
                {
                    b.Navigation("Tranches");
                });
#pragma warning restore 612, 618
        }
    }
}
